services:
  - type: web
    name: zansupermarket-backend
    runtime: python
    plan: starter
    rootDir: zansupermarket
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn zansupermarket.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DJANGO_SETTINGS_MODULE
        value: zansupermarket.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-zansupermarket-production-key-change-this
      - key: ALLOWED_HOSTS
        value: 127.0.0.1,localhost,.onrender.com,.vercel.app,supermarketzanzibar.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://supermarketzanzibar.vercel.app,https://zanzibarsupermarket.vercel.app,https://supermarketzanzibar.onrender.com
      - key: CORS_ALLOWED_ORIGIN_REGEXES
        value: ^https://.*\.vercel\.app$
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.vercel.app,https://*.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: False
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_5RNWQXv0ZgBd@ep-odd-truth-adpy5dqz-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DEFAULT_FROM_EMAIL
        value: noreply@zansupermarket.com
      - key: EMAIL_HOST
        value: smtp.example.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        value: your-smtp-user
      - key: EMAIL_HOST_PASSWORD
        value: your-smtp-password
      - key: EMAIL_USE_TLS
        value: True
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: GOOGLE_CLIENT_ID
        value: 139448352472-lam10578fsju2s23n2ffru2ugssr8pdm.apps.googleusercontent.com
      - key: STRICT_MEDIA_ROOT
        value: True
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SECURE_HSTS_SECONDS
        value: 31536000
    disks:
      - name: zansupermarket-media
        mountPath: /var/data
        sizeGB: 1
